[project]
name = "rental-system"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.nft-rentals]
path = "contracts/nft-rentals.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
